force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClientId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchases</relationshipLabel>
    <relationshipName>Purchases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/GrandTotal__c.field-meta.xml
<CustomField>
    <fullName>GrandTotal__c</fullName>
    <label>GrandTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/TotalItems__c.field-meta.xml
<CustomField>
    <fullName>TotalItems__c</fullName>
    <label>TotalItems</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/PurchaseLine__c.object-meta.xml
<CustomObject>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseLine__c/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <label>ItemId</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>PurchaseLines</relationshipLabel>
    <relationshipName>PurchaseLines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/fields/PurchaseId__c.field-meta.xml
<CustomField>
    <fullName>PurchaseId__c</fullName>
    <label>Purchase Id</label>
    <referenceTo>Purchase__c</referenceTo>
    <relationshipLabel>PurchaseLines</relationshipLabel>
    <relationshipName>PurchaseLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PurchaseLineTriggerHandlerTest.cls
@isTest
public class PurchaseLineTriggerHandlerTest {
    @isTest
    static void testUpdatePurchaseTotals() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Purchase__c purchase = new Purchase__c(ClientId__c = testAccount.Id);
        insert purchase;

        Item__c item1 = new Item__c(Name = 'Item 1', Price__c = 100);
        Item__c item2 = new Item__c(Name = 'Item 2', Price__c = 200);
        insert new List<Item__c>{ item1, item2 };

        PurchaseLine__c line1 = new PurchaseLine__c(PurchaseId__c = purchase.Id, ItemId__c = item1.Id, UnitCost__c = 100, Amount__c = 100);
        PurchaseLine__c line2 = new PurchaseLine__c(PurchaseId__c = purchase.Id, ItemId__c = item2.Id, UnitCost__c = 200, Amount__c = 200);
        insert new List<PurchaseLine__c>{ line1, line2 };

        Purchase__c updatedPurchase = [SELECT TotalItems__c, GrandTotal__c FROM Purchase__c WHERE Id = :purchase.Id];
        System.assertEquals(2, updatedPurchase.TotalItems__c);
        System.assertEquals(300, updatedPurchase.GrandTotal__c);
    }
}