force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ClientId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchases</relationshipLabel>
    <relationshipName>Purchases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/GrandTotal__c.field-meta.xml
<CustomField>
    <fullName>GrandTotal__c</fullName>
    <label>GrandTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/TotalItems__c.field-meta.xml
<CustomField>
    <fullName>TotalItems__c</fullName>
    <label>TotalItems</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/PurchaseLine__c.object-meta.xml
<CustomObject>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseLine__c/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <label>ItemId</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>PurchaseLines</relationshipLabel>
    <relationshipName>PurchaseLines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/fields/PurchaseId__c.field-meta.xml
<CustomField>
    <fullName>PurchaseId__c</fullName>
    <label>Purchase Id</label>
    <referenceTo>Purchase__c</referenceTo>
    <relationshipLabel>PurchaseLines</relationshipLabel>
    <relationshipName>PurchaseLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PurchaseControllerTest.cls
@isTest
public class PurchaseControllerTest {

    @testSetup
    static void setupTestData() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        List<Item__c> testItems = new List<Item__c>();
        testItems.add(new Item__c(Name = 'Item 1', Price__c = 10.0));
        testItems.add(new Item__c(Name = 'Item 2', Price__c = 20.0));
        insert testItems;
    }

    @isTest
    static void testCreatePurchase_Success() {
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        List<Item__c> testItems = [SELECT Id, Price__c FROM Item__c];

        Test.startTest();
        Id purchaseId = PurchaseController.createPurchase(
                new List<Id>{ testItems[0].Id, testItems[1].Id },
                testAccount.Id
        );
        Test.stopTest();

        Purchase__c purchase = [SELECT Id, ClientId__c, TotalItems__c, GrandTotal__c FROM Purchase__c WHERE Id = :purchaseId LIMIT 1];
        System.assertEquals(testAccount.Id, purchase.ClientId__c);
        System.assertEquals(2, purchase.TotalItems__c);
        System.assertEquals(30.0, purchase.GrandTotal__c);

        List<PurchaseLine__c> purchaseLines = [SELECT ItemId__c, UnitCost__c, Amount__c FROM PurchaseLine__c WHERE PurchaseId__c = :purchaseId];
        System.assertEquals(2, purchaseLines.size());
        System.assertEquals(testItems[0].Id, purchaseLines[0].ItemId__c);
        System.assertEquals(10.0, purchaseLines[0].UnitCost__c);
        System.assertEquals(10.0, purchaseLines[0].Amount__c);
    }
}